package com.artbender.service.engine.action.support;

public enum GameAction {
    FACEOFF, INIT, ATTACK, END_GAME, UPDATE_TIME, SCHEMA, DEFENSE, TEAM_COMPARE, SHOOT_PROCESS, UPDATE_STATS, FOUL, RESULT, UPDATE_STAMINA,
    INSIDE, MID, THREEPT, FREETHROW, TURNOVER, DREBOUND, BLOCK, STEAL, OFREBOUND,
    SLAMDUNK, ASSIST, MISS, SCORE, FREETR, HOME_TIMEOUT, AWAY_TIMEOUT, OTHER
}
